const LOADINGSTART='LOADING_START';
const LOADINGEND='LOADING_END';
const SEARCH='SEARCH_RULET_LIST_DATA';
const GETFORMITEMS = 'GET_FORM_ITEMS';
const SET_DATAS = 'SET_DATAS';
const setSearchObj = 'setSearchObj';
const SET_BTN_LOADING_ACTIVE = 'SET_BTN_LOADING_ACTIVE';
const SET_BTN_DLOADING_DISPLAY = 'SET_BTN_DLOADING_DISPLAY';
const BTN_REQUEST_ACTIVE = 'BTN_REQUEST_ACTIVE';
const BTN_REQUEST_DISPLAY = 'BTN_REQUEST_DISPLAY';
const SET_TYPE_DATAS = 'SET_TYPE_DATAS';
const SET_STATIC_STATUS = 'SET_STATIC_STATUS';
const SET_TEMP_SEARCH_OBJ = 'SET_TEMP_SEARCH_OBJ';

export default {
    LOADINGSTART,
    LOADINGEND,
    SEARCH,
    GETFORMITEMS,
    SET_DATAS,
    setSearchObj,
    SET_BTN_LOADING_ACTIVE,
    SET_BTN_DLOADING_DISPLAY,
    BTN_REQUEST_ACTIVE,
    BTN_REQUEST_DISPLAY,
    SET_TYPE_DATAS,
    SET_STATIC_STATUS,
    SET_TEMP_SEARCH_OBJ
}